### ISSUE TITLE
zoomToValues and zoomToDates is inaccurate when zooming across groupIntervals

### ISSUE THREAD

**Issue by dbr787** [amcharts/amcharts5#408]
**Bug description**

The zoomToValues and zoomToDates functions do not accurately zoom to the set date\value when data is dynamically grouped on a chart, and zooming the chart to\from these different group intervals.

See live example here;
Using the buttons (1Y. 30D, 7D), and changing between 1Y and 30D. The 30D button has to be clicked twice to accurately zoom to the set value.
https://codepen.io/dbr787/pen/RwQwYEW

The same issue can be seen on the live website demo below;
When clicking between the 2Y and 1M buttons, each needs to be presed twice in order to accurately zoom to the set dates\values...
https://www.amcharts.com/demos/stock-data-grouping/

From that demo, it seems that even the default am5stock.PeriodSelector has this issue, and is surely not the expected behaviour for a user.

I'd also like to know if there is some kind of workaround for this?

Cheers!

**Environment (if applicable)**
 - amCharts version 5
 - Google Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by zeroin** [comment]
It's complicated :)
The problem is, that when a different grouping interval is used, min and max of the axis changes. 
We released an update, where we fixed it in stock chart. And here is how we do it:

```
// find interval which will be used after zoom
const interval = axis.getGroupInterval($time.getDuration(period.timeUnit, period.count))
if (interval) {
  // find max of the base interval
  let endTime = axis.getIntervalMax(axis.get("baseInterval"));

  if (endTime != null) {
    // round to the future interval
    end = am5.time.round(new Date(endTime), interval.timeUnit, interval.count);
  }

  // get start
  start = am5.time.add(new Date(end), period.timeUnit, (period.count || 1) * -1);
  // first zoom (positions will still be wrong), note you should zoom instantly (that's why duration = 0)
  axis.zoomToDates(start, end, 0);
  // second zoom now it should be fine
  setTimeout(() => {
    axis.zoomToDates(start, end, 0);
  }, 10);
}```

I hope this helps, but as I said, it's complicated.

**Comment by dbr787** [comment]
Thanks @zeroin I can see the new methods were added yesterday (3rd May 2022) to [v5.2.1 in the changelog
](https://github.com/amcharts/amcharts5/blob/f7c5a701c0216c7a6c2972cb8bfd546b468b7c26/packages/shared/CHANGELOG.md#521---2022-05-03)
It appears the issue is still present in some cases, for example when changing from '1Y' to 'YTD' in the following demo, 'YTD' still needs to be clicked twice in order to correctly zoom...
https://www.amcharts.com/demos/stock-data-grouping/

**Comment by zeroin** [comment]
Thanks I will fix this in next release. YTD was handled separately and it also need a similar approach.

**Comment by martynasma** [comment]
Fixed in [5.2.3](https://github.com/amcharts/amcharts5/releases/tag/5.2.3).

## [5.2.3] - 2022-05-12

### Changed
- Upgraded versions of `pdfmake` and `xlsx` dependencies.
- Reseting `x` and `y` of the `ForceDirectedSeries` data item will make the node be not ifxed anymore.
- Tweaked styles of `StockToolbar` controls to work better with theme colors.

### Fixed
- Enclosing multi-word parameters in in-line styles were not working.
- `DateAxis` was producing an error if series had no initial data and timezone was set on a root element.
- Vertically-stacked Y-axes was incorrectly plotting related series with Y-axis set as base axis.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
